"""Stage 9 — ``render``:拼装最终讲义 markdown + HTML。

输入:
- ``work/chapters/chapters.json``:章节元数据(title / summary / key_points / image_refs)
- ``<drafts_dir>/chapter_NN.md``:每章节草稿 markdown(由 :mod:`draft` 产出,
  ``[[GEN: ...]]`` 已被 :mod:`imagegen` 替换为 ``![[gen_<uuid>.png]]``)
- ``<drafts_dir>/images/gen_<uuid>.png``:AI 配图(可能缺失)

输出:
- ``<output_dir>/<stem>.md``:拼装后的完整讲义 markdown(含 TOC)
- ``<output_dir>/<stem>.html``:渲染后的 HTML(jinja2 模板,TOC + 内嵌 CSS)

布局约定::

    <output_dir>/
    ├── <stem>.md
    ├── <stem>.html
    └── <stem>/
        ├── chapter_NN.md        (可选保留,作为参考)
        └── images/
            └── gen_<uuid>.png

行为:
1. 从 ``chapters.json`` 派生 ``video / stem``
2. 每章节:读 ``chapter_NN.md`` → 重写图像引用为标准 markdown 语法
   ``![[gen_xxx.png]]`` → ``![Image](<stem>/images/gen_xxx.png)``
3. 拼装 markdown:TOC + 各章节块(含标题 / 摘要 / 要点 / 关键帧链接 / 章节正文)
4. 用 markdown 库 + jinja2 模板生成 HTML(TOC 锚点、内嵌 CSS)
5. 所有产物路径相对 ``<stem>.md / .html`` 自身,不依赖绝对路径

依赖:
- :mod:`markdown`(md → HTML,PIP 运行时)
- jinja2 模板(字符串模板,无外部文件)
- :mod:`chapters` 的 :class:`ChaptersReport`(复用)

参考:TDD §5 数据流第 9 步 + PROJECT_DESCRIPTION §3.2 render 行 +
     CLAUDE.md §7 图片相对路径红线。
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path

import jinja2
import markdown as md_lib
from markdown.extensions.toc import TocExtension

from ..config import WorkflowConfig
from .chapters import Chapter, ChaptersReport

# ─────────────────────────────────────────────────────────────
# 常量
# ─────────────────────────────────────────────────────────────

# ``![[gen_<uuid>.png]]`` 图像 wiki-link → 标准 markdown 图片
_WIKILINK_IMG_RE = re.compile(r"!\[\[([^\]]+\.png)\]\]")

# ``[start-ends] text`` 时间戳占位(章节 md 末尾可能有)
# 允许行首空白以兼容 ``   [0.50s - 1.20s] text``
_TIMESTAMP_LINE_RE = re.compile(r"^\s*\[[^\]]*\d[^\]]*\].*$", re.MULTILINE)

# ─────────────────────────────────────────────────────────────
# Jinja2 模板(自包含 CSS)
# ─────────────────────────────────────────────────────────────

_HTML_TEMPLATE = jinja2.Template(
  """<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{{ title }}</title>
<style>
:root { color-scheme: light dark; }
body { font-family: -apple-system, "Segoe UI", "Microsoft YaHei", sans-serif;
       max-width: 920px; margin: 2rem auto; padding: 0 1.5rem;
       line-height: 1.7; color: #1a1a1a; background: #fafafa; }
@media (prefers-color-scheme: dark) {
  body { background: #1a1a1a; color: #e0e0e0; }
}
h1, h2, h3 { line-height: 1.3; }
h1 { font-size: 2rem; border-bottom: 2px solid #4a90e2; padding-bottom: 0.3rem; }
h2 { font-size: 1.5rem; margin-top: 2.5rem; color: #2a6496; }
h3 { font-size: 1.15rem; color: #3a749c; }
nav.toc { background: #f0f7ff; border: 1px solid #d0e0f0; border-radius: 6px;
          padding: 1rem 1.5rem; margin: 1.5rem 0; }
@media (prefers-color-scheme: dark) {
  nav.toc { background: #1f2a37; border-color: #2a3a4a; }
}
nav.toc h2 { margin-top: 0; font-size: 1rem; color: inherit; }
nav.toc ol { padding-left: 1.5rem; margin: 0.5rem 0 0 0; }
nav.toc a { text-decoration: none; }
code, pre { background: #f5f5f5; padding: 0.1rem 0.3rem; border-radius: 3px; }
@media (prefers-color-scheme: dark) {
  code, pre { background: #2a2a2a; }
}
img { max-width: 100%; height: auto; border-radius: 4px;
      box-shadow: 0 2px 8px rgba(0,0,0,0.1); margin: 1rem 0; }
blockquote { border-left: 4px solid #4a90e2; margin: 1rem 0;
             padding: 0.5rem 1rem; background: #f8f8f8; }
@media (prefers-color-scheme: dark) {
  blockquote { background: #252525; }
}
hr { border: 0; border-top: 1px solid #ddd; margin: 2rem 0; }
footer { margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #ddd;
         font-size: 0.85rem; color: #888; text-align: center; }
</style>
</head>
<body>
{{ body | safe }}
<footer>
  Generated by media-to-doc · {{ generated_at }}
</footer>
</body>
</html>
""",
  autoescape=False,  # 我们已在 markdown 库里 escape
)


# ─────────────────────────────────────────────────────────────
# 数据类
# ─────────────────────────────────────────────────────────────


@dataclass
class RenderOutputs:
  """整体渲染结果。"""

  video: str = ""
  course_title: str = ""
  md_path: Path | None = None
  html_path: Path | None = None
  chapters_rendered: int = 0
  image_refs_resolved: int = 0
  image_refs_missing: int = 0

  def to_dict(self) -> dict[str, object]:
    return {
      "video": self.video,
      "course_title": self.course_title,
      "md_path": str(self.md_path) if self.md_path else "",
      "html_path": str(self.html_path) if self.html_path else "",
      "chapters_rendered": self.chapters_rendered,
      "image_refs_resolved": self.image_refs_resolved,
      "image_refs_missing": self.image_refs_missing,
    }


# ─────────────────────────────────────────────────────────────
# 章节正文读取与图像引用重写
# ─────────────────────────────────────────────────────────────


def _read_chapter_body(drafts_dir: Path, idx: int) -> str:
  """读 ``chapter_NN.md`` 的正文(H1 标题行及其以下的所有内容,剥离摘要/要点块)。"""
  md_path = drafts_dir / f"chapter_{idx:02d}.md"
  if not md_path.exists():
    return ""
  text = md_path.read_text(encoding="utf-8")
  # 找到 ``\n---\n`` 之后的正文(pipeline 自己的 ``_render_draft_markdown`` 模式)
  parts = text.split("\n---\n", 1)
  return parts[1].lstrip("\n").rstrip() if len(parts) == 2 else text.rstrip()


def _rewrite_image_refs(body: str, image_prefix: str, drafts_dir: Path) -> tuple[str, int, int]:
  """把 ``![[gen_xxx.png]]`` 改写为 ``![Image](<image_prefix>/gen_xxx.png)``。

  - 缺失的图像(不在 ``drafts_dir/images/``)→ 改写为警告文字,不输出 broken link
  - 返回 (rewritten, resolved_count, missing_count)
  """
  resolved = 0
  missing = 0

  def _repl(m: re.Match[str]) -> str:
    nonlocal resolved, missing
    name = m.group(1).strip()
    img_path = drafts_dir / "images" / name
    if img_path.exists():
      resolved += 1
      return f"![Image]({image_prefix}/{name})"
    missing += 1
    return f"_⚠️ 配图缺失:{name}_"

  out = _WIKILINK_IMG_RE.sub(_repl, body)
  return out, resolved, missing


def _strip_timestamp_lines(body: str) -> str:
  """去掉 ``[start-ends] text`` 形式的时间戳占位(如果是逐字稿引用残留)。"""
  return _TIMESTAMP_LINE_RE.sub("", body)


# ─────────────────────────────────────────────────────────────
# markdown / HTML 渲染
# ─────────────────────────────────────────────────────────────


def _build_toc(chapters: list[Chapter]) -> str:
  """生成 ``\n- [title](#anchor)\n`` 形式的 TOC markdown。"""
  lines: list[str] = []
  lines.append("## 目录")
  lines.append("")
  for ch in chapters:
    # markdown 库的 toc 扩展会自动从 H1/H2 派生 anchor
    # 我们这里手工做 link,文本对应 ``## {title}``
    slug = _slugify(ch.title)
    lines.append(f"- [{ch.title}](#{slug})")
  lines.append("")
  return "\n".join(lines)


_SLUG_RE = re.compile(r"[^a-zA-Z0-9\u4e00-\u9fff\-_]+")


def _slugify(text: str) -> str:
  """生成 markdown 锚点兼容的 slug:小写 + 非字面字符替 ``-``。"""
  s = text.strip().lower()
  s = _SLUG_RE.sub("-", s)
  s = s.strip("-")
  return s or "section"


def _render_markdown_to_html(md_text: str) -> str:
  """md → html(启用 toc 扩展 + fenced_code + tables)。"""
  md = md_lib.Markdown(
    extensions=[
      "fenced_code",
      "tables",
      TocExtension(toc_depth="2-3"),
    ],
    output_format="html",
  )
  return md.convert(md_text)


def _wrap_html_body(body_html: str, title: str) -> str:
  """用 jinja2 模板把 body 包成完整 HTML。"""
  import datetime as _dt

  return _HTML_TEMPLATE.render(
    title=title,
    body=body_html,
    generated_at=_dt.datetime.now().strftime("%Y-%m-%d %H:%M"),
  )


# ─────────────────────────────────────────────────────────────
# Markdown 拼装
# ─────────────────────────────────────────────────────────────


def _assemble_markdown(
  report: ChaptersReport,
  body_lookup: dict[int, str],
) -> str:
  """拼装完整 markdown:TOC + 课程标题 + 每章节块。"""
  parts: list[str] = []
  parts.append(f"# {report.video or '课程讲义'}")
  parts.append("")
  parts.append("> 本讲义由 media-to-doc 流水线自动生成。")
  parts.append("")
  parts.append(_build_toc(report.chapters))
  parts.append("---")
  parts.append("")

  for ch in report.chapters:
    parts.append(f"## {ch.title}")
    parts.append("")
    if ch.summary:
      parts.append(f"> **摘要**:{ch.summary}")
      parts.append("")
    if ch.key_points:
      parts.append("**关键要点**:")
      parts.append("")
      for p in ch.key_points:
        parts.append(f"- {p}")
      parts.append("")
    if ch.image_refs:
      parts.append("**引用关键帧**:")
      parts.append("")
      for ts in ch.image_refs:
        parts.append(f"- {ts:.2f}s → `frame_{int(ts * 1000):09d}.jpg`")
      parts.append("")
    body = body_lookup.get(ch.idx, "")
    if body:
      body = _strip_timestamp_lines(body).strip()
      parts.append(body)
      parts.append("")
    parts.append("---")
    parts.append("")
  return "\n".join(parts).rstrip() + "\n"


# ─────────────────────────────────────────────────────────────
# 公开 API
# ─────────────────────────────────────────────────────────────


def load_chapters_report(path: Path) -> ChaptersReport:
  """从 ``chapters.json`` 反序列化(与 ``draft.py`` 等价的 helper)。"""
  data = json.loads(path.read_text(encoding="utf-8"))
  chapters: list[Chapter] = []
  for raw in data.get("chapters", []):
    payload = {k: v for k, v in raw.items() if k != "duration_seconds"}
    chapters.append(Chapter(**payload))
  return ChaptersReport(
    video=data.get("video", ""),
    provider=data.get("provider", ""),
    model=data.get("model", ""),
    chapters=chapters,
  )


def render_outputs(
  work: Path,
  config: WorkflowConfig | None = None,
  *,
  chapters_dir: Path | None = None,
  drafts_dir: Path | None = None,
  output_dir: Path | None = None,
  output_stem: str | None = None,
  write_html: bool = True,
) -> RenderOutputs:
  """Stage 9:拼装最终讲义 markdown (+ 可选 HTML)。

  Parameters
  ----------
  work : Path
    work 根目录
  config : WorkflowConfig | None
    配置(预留)
  chapters_dir : Path | None
    ``chapters.json`` 所在目录(默认 ``<work>/chapters``)
  drafts_dir : Path | None
    ``chapter_NN.md`` 所在目录(默认 ``<chapters_dir>/raw/<video_stem>``)
  output_dir : Path | None
    最终产物目录(默认 ``<drafts_dir>/..`` — 即 ``<chapters_dir>/raw/``)
  output_stem : str | None
    输出文件名(默认 = ``drafts_dir.name``)
  write_html : bool
    是否同时写 HTML(默认 True)

  Returns
  -------
  RenderOutputs
    含 md_path / html_path / 渲染统计
  """
  _ = config
  c_dir = chapters_dir or (work / "chapters")
  chapters_json = c_dir / "chapters.json"
  if not chapters_json.exists():
    raise FileNotFoundError(
      f"找不到 {chapters_json};请先跑 chapters stage"
    )
  report = load_chapters_report(chapters_json)
  if not report.chapters:
    raise ValueError("chapters.json 章节列表为空,无法渲染")

  if drafts_dir is None:
    drafts_dir = c_dir / "raw" / (report.video or "output")
  if not drafts_dir.exists():
    raise FileNotFoundError(
      f"找不到 drafts_dir {drafts_dir};请先跑 draft stage"
    )
  if output_dir is None:
    output_dir = drafts_dir.parent
  if output_stem is None:
    output_stem = drafts_dir.name

  output_dir.mkdir(parents=True, exist_ok=True)

  # 计算图像相对路径前缀(从 ``<output_dir>/<stem>.md`` 到 ``images/``):
  # ``image_prefix`` = "<stem>/images"
  image_prefix = f"{output_stem}/images"

  # 读取每章节正文 + 重写图像引用
  body_lookup: dict[int, str] = {}
  resolved_total = 0
  missing_total = 0
  for ch in report.chapters:
    raw_body = _read_chapter_body(drafts_dir, ch.idx)
    if not raw_body:
      continue
    rewritten, resolved, missing = _rewrite_image_refs(
      raw_body, image_prefix, drafts_dir
    )
    body_lookup[ch.idx] = rewritten
    resolved_total += resolved
    missing_total += missing

  # 拼装 markdown
  md_text = _assemble_markdown(report, body_lookup)
  md_path = output_dir / f"{output_stem}.md"
  md_path.write_text(md_text, encoding="utf-8")

  html_path: Path | None = None
  if write_html:
    body_html = _render_markdown_to_html(md_text)
    full_html = _wrap_html_body(body_html, report.video or output_stem)
    html_path = output_dir / f"{output_stem}.html"
    html_path.write_text(full_html, encoding="utf-8")

  return RenderOutputs(
    video=report.video,
    course_title=output_stem,
    md_path=md_path,
    html_path=html_path,
    chapters_rendered=len(body_lookup),
    image_refs_resolved=resolved_total,
    image_refs_missing=missing_total,
  )


def render_html(md_path: Path, *, html_path: Path | None = None) -> Path:
  """独立函数:从现有 ``.md`` 渲染 ``.html``(便于 ``read_lecture`` MCP 工具调用)。

  Parameters
  ----------
  md_path : Path
    已存在的 ``<stem>.md`` 路径
  html_path : Path | None
    输出路径(默认 ``<md_path>.stem``.html)

  Returns
  -------
  Path
    实际写入的 html 路径
  """
  if not md_path.exists():
    raise FileNotFoundError(f"找不到 {md_path}")
  md_text = md_path.read_text(encoding="utf-8")
  body_html = _render_markdown_to_html(md_text)
  title = md_path.stem
  full_html = _wrap_html_body(body_html, title)
  target = html_path or md_path.with_suffix(".html")
  target.write_text(full_html, encoding="utf-8")
  return target


__all__ = [
  "RenderOutputs",
  "load_chapters_report",
  "render_outputs",
  "render_html",
]
